### ISSUE TITLE
Compile in Xcode 4.2

### ISSUE THREAD

**Issue by ottost** [stig/json-framework#103]
The Framework show several errors in TweetStream example (include image):

http://cl.ly/AzJL

Errors like:
- SBJsonStreamParser.m:63:3: error: 'release' is unavailable: not available in automatic reference counting mode [3]
- SBJsonStreamParser.m:63:3:{63:14-63:21}: error: ARC forbids explicit message send of 'release' [4]
- SBJsonStreamParser.m:171:5: error: 'NSAutoreleasePool' is unavailable: not available in automatic reference counting mode [3]
- SBJsonStreamParserAccumulator.m:37:6:{37:12-37:19}: error: ARC forbids explicit message send of 'release' [4]

etc.

Thanks in advance!
